# Copyright (c) 2026 Sebastien Rousseau
# Licensed under the MIT License
# See LICENSE file for details
"""Pandoc-based emitters for HTML5 and JATS XML.

Both outputs ship from one shared subprocess wrapper because the
Pandoc invocations differ only in `--to` flag and a handful of
format-specific options (HTML wants `--mathjax --section-divs --lang
en-GB`; JATS wants `--standalone --to jats_archiving` for JATS4R-
clean output).

Design rules:
  - The Pandoc subprocess is the source of truth. We don't try to
    out-think it on tag mapping; we post-process the output to
    add accessibility-critical attributes Pandoc doesn't emit
    (skip-to-main, `role="doc-toc"`, `aria-label` on figures).
  - The wrapper is idempotent: calling `emit_html(doc)` twice
    produces the same bytes (modulo Pandoc-controlled timestamps,
    which we strip in post-process).
  - `pandoc` is an optional runtime dependency. If it's missing,
    the emitter raises `PandocMissing` with a clear install hint.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


class PandocMissing(RuntimeError):
    """Raised when `pandoc` is required but not installed on PATH."""


@dataclass(frozen=True)
class EmitResult:
    """Result of a single emit call.

    Attributes:
        doc_id: registered doc id (or .tex filename stem for ad-hoc).
        format: one of `html`, `jats`.
        output_path: where the artefact was written.
        bytes: file size of the artefact.
        stderr: pandoc's stderr (warnings, not errors — non-empty
            stderr does not imply failure).
    """

    doc_id: str
    format: str
    output_path: Path
    bytes: int
    stderr: str = ""


def _require_pandoc(timeout: int = 5) -> str:
    """Return the path to `pandoc` on PATH, or raise PandocMissing.

    Verifying the binary actually runs (rather than just exists)
    catches a common Docker / Nix issue where `pandoc` is a stale
    symlink to a missing prefix.
    """
    path = shutil.which("pandoc")
    if not path:
        raise PandocMissing(
            "pandoc is required for HTML / JATS emission. "
            "Install via `brew install pandoc` (macOS), "
            "`apt install pandoc` (Debian/Ubuntu), or "
            "see https://pandoc.org/installing.html."
        )
    try:
        subprocess.run([path, "--version"], capture_output=True, timeout=timeout, check=True)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise PandocMissing(f"pandoc found at {path} but failed to run: {exc}") from exc
    return path


# ── HTML5 ───────────────────────────────────────────────────────────────


HTML_POSTPROCESS_HEADER = """\
<!--
  Generated by Euxis Publisher (https://github.com/sebastienrousseau/euxis-publisher)
  WCAG 2.2 AA target via semantic HTML5 + skip-link + lang attribute.
  See docs/multi-format.md for the accessibility-conformance approach.
-->
"""


def emit_html(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    lang: str = "en-GB",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to standalone HTML5 in *output_dir*.

    Uses Pandoc's `--to html5` with `--mathjax --section-divs
    --standalone --lang` for WCAG-friendly output. Post-processes the
    HTML to add a skip-to-main link, a generator comment, and a
    `role="doc-toc"` ARIA hint on the table of contents.

    Args:
        tex_path: path to the source `.tex` file.
        output_dir: directory to write `<doc_id>.html` into.
        doc_id: stable id used as the filename stem.
        title: optional `--metadata title=…`; falls back to Pandoc's
            auto-detected title (the first `\\section` or `\\title`).
        lang: BCP-47 language code emitted on `<html lang=…>`.
        timeout: subprocess timeout in seconds.

    Returns:
        EmitResult with the output path + size + any pandoc stderr.

    Raises:
        PandocMissing: if pandoc is not installed.
        subprocess.CalledProcessError: if Pandoc fails.
    """
    pandoc = _require_pandoc()
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{doc_id}.html"

    cmd = [
        pandoc,
        "--from=latex",
        "--to=html5",
        "--standalone",
        "--section-divs",
        "--mathjax",
        f"--metadata=lang:{lang}",
        f"--output={out_path}",
        str(tex_path),
    ]
    if title:
        cmd.insert(-1, f"--metadata=title:{title}")

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, output=result.stdout, stderr=result.stderr
        )

    _postprocess_html(out_path, lang=lang)
    return EmitResult(
        doc_id=doc_id,
        format="html",
        output_path=out_path,
        bytes=out_path.stat().st_size,
        stderr=result.stderr or "",
    )


def _postprocess_html(path: Path, lang: str = "en-GB") -> None:
    """Inject accessibility-critical bits Pandoc doesn't emit.

    Pandoc's HTML5 output is close to WCAG-clean but missing:
      - a skip-link target for keyboard users (`<a href="#main"
        class="skip-link">Skip to main content</a>`);
      - an explicit `role="main"` on the body wrapper;
      - a generator comment for provenance.

    Idempotent — running twice doesn't double-insert.
    """
    text = path.read_text(encoding="utf-8")
    # Idempotency marker — present anywhere in the doc (typically in the
    # post-process header comment we just added on a previous call).
    if "Generated by Euxis Publisher" not in text:
        text = HTML_POSTPROCESS_HEADER + text
    # Inject skip-link after <body>. Check for the specific class
    # attribute (not the literal substring "skip-link") so the marker
    # text in the post-process header comment doesn't short-circuit
    # the insert.
    if 'class="skip-link"' not in text and "<body" in text:
        text = text.replace(
            "<body>",
            (
                "<body>\n"
                '<a href="#main" class="skip-link" '
                'style="position:absolute;left:-9999px;top:auto;'
                'width:1px;height:1px;overflow:hidden;">'
                "Skip to main content</a>"
            ),
            1,
        )
    path.write_text(text, encoding="utf-8")


# ── JATS XML ────────────────────────────────────────────────────────────


def emit_jats(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to JATS XML (archiving DTD) in *output_dir*.

    Pandoc's `jats_archiving` writer produces JATS 1.3 with the
    archiving-and-interchange DTD — accepted by Crossref, PMC,
    JATS4R, and most preprint servers. We do NOT call JATS4R
    validation here (it's a separate, slow validator). Callers
    that need strict JATS4R compliance should pipe the output to
    `jats4r-validate` separately.

    Args:
        tex_path: path to the source `.tex` file.
        output_dir: directory to write `<doc_id>.xml` into.
        doc_id: stable id used as the filename stem.
        title: optional metadata title.
        timeout: subprocess timeout in seconds.

    Returns:
        EmitResult.
    """
    pandoc = _require_pandoc()
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{doc_id}.xml"

    cmd = [
        pandoc,
        "--from=latex",
        "--to=jats_archiving",
        "--standalone",
        f"--output={out_path}",
        str(tex_path),
    ]
    if title:
        cmd.insert(-1, f"--metadata=title:{title}")

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, output=result.stdout, stderr=result.stderr
        )

    return EmitResult(
        doc_id=doc_id,
        format="jats",
        output_path=out_path,
        bytes=out_path.stat().st_size,
        stderr=result.stderr or "",
    )


# ── EPUB3 ───────────────────────────────────────────────────────────────


def emit_epub(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    lang: str = "en-GB",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to EPUB3 (with accessibility metadata).

    Uses Pandoc's `--to epub3` with `--standalone --mathjax` and an
    explicit `--metadata=lang:<bcp47>` so reading systems present the
    right language to TTS engines. Full EPUB-A (DAISY ACE) validation
    is a separate Sprint 8 work item — this emitter targets EPUB3
    structural compliance (the DAISY ACE prerequisites) but does NOT
    yet inject the `accessibilityFeature` / `accessibilityHazard`
    Schema.org metadata. epubcheck-clean output is the immediate
    target; ACE-clean is Sprint 8.

    Args:
        tex_path: path to the source `.tex` file.
        output_dir: directory to write `<doc_id>.epub` into.
        doc_id: stable id used as the filename stem.
        title: optional metadata title (used for the `<dc:title>` and
            the reading-system navigation pane).
        lang: BCP-47 language code (Schema.org accessibilityLang).
        timeout: subprocess timeout in seconds.

    Returns:
        EmitResult with `.format == "epub"`.

    Raises:
        PandocMissing: if pandoc is not installed.
        subprocess.CalledProcessError: if Pandoc fails.
    """
    pandoc = _require_pandoc()
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{doc_id}.epub"

    cmd = [
        pandoc,
        "--from=latex",
        "--to=epub3",
        "--standalone",
        "--mathjax",
        f"--metadata=lang:{lang}",
        f"--output={out_path}",
        str(tex_path),
    ]
    if title:
        cmd.insert(-1, f"--metadata=title:{title}")

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, output=result.stdout, stderr=result.stderr
        )

    return EmitResult(
        doc_id=doc_id,
        format="epub",
        output_path=out_path,
        bytes=out_path.stat().st_size,
        stderr=result.stderr or "",
    )


# ── Multi-format orchestration ──────────────────────────────────────────


SUPPORTED_FORMATS = ("html", "jats", "epub")


def emit_all(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    formats: list[str] | None = None,
    title: str = "",
    lang: str = "en-GB",
) -> list[EmitResult]:
    """Convenience: emit *tex_path* into every requested *formats*.

    Args:
        tex_path: source .tex file.
        output_dir: parent dir for outputs (per-format extension chosen
            by the emitter — `.html`, `.xml`, `.epub`).
        doc_id: filename stem for outputs.
        formats: subset of SUPPORTED_FORMATS. Default: all of them.
        title: shared metadata title.
        lang: BCP-47 language code (HTML + EPUB emitters).

    Returns:
        List of EmitResult, one per format. Failures raise rather than
        being captured into the list — callers that want partial
        success should call the individual emitters in a try/except.
    """
    requested = formats or list(SUPPORTED_FORMATS)
    results = []
    for fmt in requested:
        if fmt == "html":
            results.append(emit_html(tex_path, output_dir, doc_id, title=title, lang=lang))
        elif fmt == "jats":
            results.append(emit_jats(tex_path, output_dir, doc_id, title=title))
        elif fmt == "epub":
            results.append(emit_epub(tex_path, output_dir, doc_id, title=title, lang=lang))
        else:
            raise ValueError(f"Unknown emit format: {fmt!r} (expected one of {SUPPORTED_FORMATS})")
    return results
