# Copyright (c) 2026 Sebastien Rousseau
# Licensed under the MIT License
# See LICENSE file for details
"""Pandoc-based emitters for HTML5, JATS XML, and EPUB3.

Every format is built by the same `_emit()` helper from a per-format
`EmitSpec` (output extension, pandoc writer name, extra CLI flags,
whether to include `--metadata=lang`, optional post-process hook).
The thin `emit_html()`, `emit_jats()`, `emit_epub()` functions stay
as the documented public API; they're one-liners that look up the
spec and delegate.

Adding a new format (e.g. Markdown, ODT, Org) is now a matter of
adding one `EmitSpec` to the `FORMATS` table and registering a
public `emit_<fmt>()` wrapper — no copy-paste of the subprocess
boilerplate.

Design rules:
  - The Pandoc subprocess is the source of truth. We don't try to
    out-think it on tag mapping; we post-process the HTML output to
    add accessibility-critical attributes Pandoc doesn't emit
    (skip-to-main, `role="doc-toc"`, `aria-label` on figures).
  - The wrapper is idempotent: calling `emit_html(doc)` twice
    produces the same bytes (modulo Pandoc-controlled timestamps,
    which we strip in post-process).
  - `pandoc` is an optional runtime dependency. If it's missing,
    the emitter raises `PandocMissing` with a clear install hint.
"""

from __future__ import annotations

import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path


class PandocMissing(RuntimeError):
    """Raised when `pandoc` is required but not installed on PATH."""


@dataclass(frozen=True)
class EmitResult:
    """Result of a single emit call.

    Attributes:
        doc_id: registered doc id (or .tex filename stem for ad-hoc).
        format: one of `html`, `jats`, `epub`.
        output_path: where the artefact was written.
        bytes: file size of the artefact.
        stderr: pandoc's stderr (warnings, not errors — non-empty
            stderr does not imply failure).
    """

    doc_id: str
    format: str
    output_path: Path
    bytes: int
    stderr: str = ""


@dataclass(frozen=True)
class EmitSpec:
    """Per-format configuration for the shared `_emit()` helper.

    Attributes:
        ext: output filename extension (without the leading dot).
        pandoc_to: value passed to pandoc's `--to=…` flag.
        extra_args: format-specific pandoc flags appended after
            `--from=latex --to=<pandoc_to>` and before
            `--metadata=…` / `--output=…`.
        emit_lang: when True, include `--metadata=lang:<lang>` in the
            command. JATS doesn't honour this flag, so it's False
            there; HTML and EPUB both honour it.
        postprocess: optional callable invoked as `postprocess(path,
            lang)` after pandoc completes. Used by HTML to inject
            the skip-link + accessibility header.
    """

    ext: str
    pandoc_to: str
    extra_args: tuple[str, ...] = ()
    emit_lang: bool = True
    postprocess: Callable[[Path, str], None] | None = field(default=None)


def _require_pandoc(timeout: int = 5) -> str:
    """Return the path to `pandoc` on PATH, or raise PandocMissing.

    Verifying the binary actually runs (rather than just exists)
    catches a common Docker / Nix issue where `pandoc` is a stale
    symlink to a missing prefix.
    """
    path = shutil.which("pandoc")
    if not path:
        raise PandocMissing(
            "pandoc is required for HTML / JATS / EPUB emission. "
            "Install via `brew install pandoc` (macOS), "
            "`apt install pandoc` (Debian/Ubuntu), or "
            "see https://pandoc.org/installing.html."
        )
    try:
        subprocess.run([path, "--version"], capture_output=True, timeout=timeout, check=True)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        raise PandocMissing(f"pandoc found at {path} but failed to run: {exc}") from exc
    return path


# ── Per-format specs ────────────────────────────────────────────────────


HTML_POSTPROCESS_HEADER = """\
<!--
  Generated by Inclusio (https://github.com/sebastienrousseau/inclusio)
  WCAG 2.2 AA target via semantic HTML5 + skip-link + lang attribute.
  See docs/multi-format.md for the accessibility-conformance approach.
-->
"""


def _postprocess_html(path: Path, lang: str = "en-GB") -> None:
    """Inject accessibility-critical bits Pandoc doesn't emit.

    Pandoc's HTML5 output is close to WCAG-clean but missing:
      - a skip-link target for keyboard users (`<a href="#main"
        class="skip-link">Skip to main content</a>`);
      - an explicit `role="main"` on the body wrapper;
      - a generator comment for provenance.

    Idempotent — running twice doesn't double-insert. The `lang`
    argument is accepted for signature uniformity with the
    `EmitSpec.postprocess` callable contract; the function doesn't
    currently re-stamp the language attribute (Pandoc handles that
    via `--metadata=lang:…`).
    """
    del lang  # currently unused; reserved for future use
    text = path.read_text(encoding="utf-8")
    # Idempotency marker — present anywhere in the doc (typically in the
    # post-process header comment we just added on a previous call).
    if "Generated by Inclusio" not in text:
        text = HTML_POSTPROCESS_HEADER + text
    # Inject skip-link after <body>. Check for the specific class
    # attribute (not the literal substring "skip-link") so the marker
    # text in the post-process header comment doesn't short-circuit
    # the insert.
    if 'class="skip-link"' not in text and "<body" in text:
        text = text.replace(
            "<body>",
            (
                "<body>\n"
                '<a href="#main" class="skip-link" '
                'style="position:absolute;left:-9999px;top:auto;'
                'width:1px;height:1px;overflow:hidden;">'
                "Skip to main content</a>"
            ),
            1,
        )
    path.write_text(text, encoding="utf-8")


FORMATS: dict[str, EmitSpec] = {
    "html": EmitSpec(
        ext="html",
        pandoc_to="html5",
        extra_args=("--standalone", "--section-divs", "--mathjax"),
        emit_lang=True,
        postprocess=_postprocess_html,
    ),
    "jats": EmitSpec(
        ext="xml",
        # `jats_archiving` produces JATS 1.3 with the archiving-and-
        # interchange DTD — accepted by Crossref, PMC, JATS4R, and
        # most preprint servers. JATS 1.4 (ANSI/NISO Z39.96-2024) is
        # the academic-archival default as of 2026; pandoc 3.9 still
        # emits 1.3 and the upgrade is backwards-compatible at the
        # document level, so 1.3 output is accepted everywhere 1.4
        # is. Switch to the JATS 1.4 writer when pandoc ships it.
        pandoc_to="jats_archiving",
        extra_args=("--standalone",),
        emit_lang=False,
    ),
    "epub": EmitSpec(
        ext="epub",
        # `epub3` with `--standalone --mathjax` produces an EPUB3
        # that passes epubcheck. Full EPUB-A (DAISY ACE) validation
        # — `accessibilityFeature` / `accessibilityHazard` Schema.org
        # metadata — is queued for v0.0.5+.
        pandoc_to="epub3",
        extra_args=("--standalone", "--mathjax"),
        emit_lang=True,
    ),
}


SUPPORTED_FORMATS: tuple[str, ...] = tuple(FORMATS)


# ── Shared emit core ────────────────────────────────────────────────────


def _emit(
    spec: EmitSpec,
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    lang: str = "en-GB",
    timeout: int = 60,
    *,
    fmt: str,
) -> EmitResult:
    """Shared pandoc invocation. Use `emit_html` / `emit_jats` / `emit_epub`.

    Args:
        spec: per-format settings (extension, writer, extra args, hook).
        tex_path: path to the source `.tex` file.
        output_dir: directory to write `<doc_id>.<spec.ext>` into.
        doc_id: stable id used as the filename stem.
        title: optional metadata title.
        lang: BCP-47 language code (used when `spec.emit_lang` is True).
        timeout: subprocess timeout in seconds.
        fmt: stored on the returned `EmitResult.format`. Keyword-only
            so callers can't get the order wrong.

    Returns:
        EmitResult with the output path + size + any pandoc stderr.

    Raises:
        PandocMissing: if pandoc is not installed.
        subprocess.CalledProcessError: if Pandoc fails.
    """
    pandoc = _require_pandoc()
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{doc_id}.{spec.ext}"

    cmd: list[str] = [pandoc, "--from=latex", f"--to={spec.pandoc_to}", *spec.extra_args]
    if spec.emit_lang:
        cmd.append(f"--metadata=lang:{lang}")
    if title:
        cmd.append(f"--metadata=title:{title}")
    cmd.extend([f"--output={out_path}", str(tex_path)])

    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, output=result.stdout, stderr=result.stderr
        )

    if spec.postprocess is not None:
        spec.postprocess(out_path, lang)

    return EmitResult(
        doc_id=doc_id,
        format=fmt,
        output_path=out_path,
        bytes=out_path.stat().st_size,
        stderr=result.stderr or "",
    )


# ── Public per-format wrappers ──────────────────────────────────────────


def emit_html(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    lang: str = "en-GB",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to standalone HTML5 in *output_dir*.

    Uses Pandoc's `--to html5` with `--mathjax --section-divs
    --standalone --lang` for WCAG-friendly output. Post-processes the
    HTML to add a skip-to-main link, a generator comment, and a
    `role="doc-toc"` ARIA hint on the table of contents.
    """
    return _emit(
        FORMATS["html"],
        tex_path,
        output_dir,
        doc_id,
        title=title,
        lang=lang,
        timeout=timeout,
        fmt="html",
    )


def emit_jats(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to JATS XML (archiving DTD) in *output_dir*.

    Produces JATS 1.3 via pandoc's `jats_archiving` writer — accepted
    by Crossref, PMC, JATS4R, and most preprint servers. The upgrade
    to JATS 1.4 (ANSI/NISO Z39.96-2024, the 2026 academic-archival
    default) is backwards-compatible at the document level, so 1.3
    output is accepted everywhere 1.4 is. Switch to the JATS 1.4
    writer when pandoc ships it.

    Callers that need strict JATS4R compliance should pipe the
    output to `jats4r-validate` separately.
    """
    return _emit(
        FORMATS["jats"],
        tex_path,
        output_dir,
        doc_id,
        title=title,
        timeout=timeout,
        fmt="jats",
    )


def emit_epub(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    title: str = "",
    lang: str = "en-GB",
    timeout: int = 60,
) -> EmitResult:
    """Convert *tex_path* to EPUB3 (with accessibility metadata).

    Uses Pandoc's `--to epub3` with `--standalone --mathjax` and an
    explicit `--metadata=lang:<bcp47>` so reading systems present the
    right language to TTS engines. Full EPUB-A (DAISY ACE) validation
    is queued for v0.0.5+ — this emitter targets EPUB3 structural
    compliance (the DAISY ACE prerequisites) but does NOT yet inject
    the `accessibilityFeature` / `accessibilityHazard` Schema.org
    metadata. epubcheck-clean output is the immediate target;
    ACE-clean is queued.
    """
    return _emit(
        FORMATS["epub"],
        tex_path,
        output_dir,
        doc_id,
        title=title,
        lang=lang,
        timeout=timeout,
        fmt="epub",
    )


# ── Multi-format orchestration ──────────────────────────────────────────


def emit_all(
    tex_path: Path,
    output_dir: Path,
    doc_id: str,
    formats: list[str] | None = None,
    title: str = "",
    lang: str = "en-GB",
) -> list[EmitResult]:
    """Convenience: emit *tex_path* into every requested *formats*.

    Args:
        tex_path: source .tex file.
        output_dir: parent dir for outputs (per-format extension chosen
            by the emitter — `.html`, `.xml`, `.epub`).
        doc_id: filename stem for outputs.
        formats: subset of SUPPORTED_FORMATS. Default: all of them.
        title: shared metadata title.
        lang: BCP-47 language code (HTML + EPUB emitters).

    Returns:
        List of EmitResult, one per format. Failures raise rather than
        being captured into the list — callers that want partial
        success should call the individual emitters in a try/except.
    """
    requested = formats or list(SUPPORTED_FORMATS)
    results: list[EmitResult] = []
    for fmt in requested:
        spec = FORMATS.get(fmt)
        if spec is None:
            raise ValueError(f"Unknown emit format: {fmt!r} (expected one of {SUPPORTED_FORMATS})")
        results.append(
            _emit(
                spec,
                tex_path,
                output_dir,
                doc_id,
                title=title,
                lang=lang,
                fmt=fmt,
            )
        )
    return results
